# Spring Boot application properties
# If problems setting up the database, check the .env file for correct credentials and URL (fix: .env file must be running in the terminal for the environment variables to be set)
# Here is command to do so:
# set -a; source .env; set +a; ./mvnw spring-boot:run
# set -a; source .env; set +a; ./mvnw test
spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.example.sportslivev1.auth=DEBUG
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
